/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-07-22 21:53:01 UTC)
 * on 2014-08-18 at 06:23:24 UTC 
 * Modify at your own risk.
 */

package com.uet.mhst.itemendpoint.model;

/**
 * Model definition for Vote.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the itemendpoint. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Vote extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Key id;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String idfb;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Item item;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean up;

  /**
   * @return value or {@code null} for none
   */
  public Key getId() {
    return id;
  }

  /**
   * @param id id or {@code null} for none
   */
  public Vote setId(Key id) {
    this.id = id;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getIdfb() {
    return idfb;
  }

  /**
   * @param idfb idfb or {@code null} for none
   */
  public Vote setIdfb(java.lang.String idfb) {
    this.idfb = idfb;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public Item getItem() {
    return item;
  }

  /**
   * @param item item or {@code null} for none
   */
  public Vote setItem(Item item) {
    this.item = item;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getUp() {
    return up;
  }

  /**
   * @param up up or {@code null} for none
   */
  public Vote setUp(java.lang.Boolean up) {
    this.up = up;
    return this;
  }

  @Override
  public Vote set(String fieldName, Object value) {
    return (Vote) super.set(fieldName, value);
  }

  @Override
  public Vote clone() {
    return (Vote) super.clone();
  }

}
